name: Go

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.24'

      - name: Build server
        run: go build ./cmd/server
      - name: Build client
        run: GOOS=js GOARCH=wasm go build ./cmd/client

      - name: Test
        run: go test -v ./...

      - run: "go test -coverprofile=coverage.out -covermode=count ./..."
      - uses: seriousben/go-patch-cover-action@v1
